sources:
  - name: uniswap3
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3
        retry: 5
    transforms:
      - autoPagination: {}
  - name: uniswap2
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2
        retry: 5
    transforms:
      - autoPagination: {}
plugins:
  - pollingLive:
      defaultInterval: 1000
documents:
  - ./graphql/GetPoolsUniswap.gql
  - ./graphql/GetPoolsUniswapLive.gql
